var $portfolio;var $masonry_block;var $portfolio_selectors;var $blog;$=jQuery.noConflict();$(document).ready(function(){"use strict";jQuery('input, textarea').placeholder({customClass:'my-placeholder'});jQuery('.inner-top').smoothScroll({speed:900,offset:-68});SetResizeHeaderMenu();IpadMobileHover();var isMobile=false;var isiPhoneiPad=false;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){isMobile=true;}
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){isiPhoneiPad=true;}
if(!isMobile){jQuery(".top-cart a.shopping-cart, .cart-content").hover(function(){jQuery(".cart-content").css('opacity','1');jQuery(".cart-content").css('visibility','visible');},function(){jQuery(".cart-content").css('opacity','0');jQuery(".cart-content").css('visibility','hidden');});jQuery(document).on({mouseenter:function(){jQuery(".cart-content").css('opacity','1');jQuery(".cart-content").css('visibility','visible');},mouseleave:function(){jQuery(".cart-content").css('opacity','0');jQuery(".cart-content").css('visibility','hidden');}},".top-cart a.shopping-cart, .cart-content");}
if(isiPhoneiPad){jQuery(".video-wrapper").css('display','none');}
jQuery(".top-cart a.shopping-cart").click(function(){if($('.cart-content').css('visibility')=='visible'){jQuery(".cart-content").css('opacity','0');jQuery(".cart-content").css('visibility','hidden');}
else{jQuery(".cart-content").css('opacity','1');jQuery(".cart-content").css('visibility','visible');}});if($(window).scrollTop()>10){$('nav').addClass('shrink-nav');}else{$('nav').removeClass('shrink-nav');}
if(Modernizr.touch){$(".close-overlay").removeClass("hidden");$(".porfilio-item").click(function(e){if(!$(this).hasClass("hover")){$(this).addClass("hover");}});$(".close-overlay").click(function(e){e.preventDefault();e.stopPropagation();if($(this).closest(".porfilio-item").hasClass("hover")){$(this).closest(".porfilio-item").removeClass("hover");}});}else{$(".porfilio-item").mouseenter(function(){$(this).addClass("hover");}).mouseleave(function(){$(this).removeClass("hover");});}
$portfolio=$('.masonry-items');$portfolio.imagesLoaded(function(){$portfolio.isotope({itemSelector:'li',layoutMode:'masonry'});});$masonry_block=$('.masonry-block-items');$masonry_block.imagesLoaded(function(){$masonry_block.isotope({itemSelector:'li',layoutMode:'masonry'});});$portfolio_selectors=$('.portfolio-filter > li > a');$portfolio_selectors.on('click',function(){$portfolio_selectors.parent().removeClass('active');$(this).parent().addClass('active');var selector=$(this).attr('data-filter');$portfolio.isotope({filter:selector});return false;});$blog=$('.blog-masonry');$blog.imagesLoaded(function(){$blog.isotope({itemSelector:'.blog-listing',layoutMode:'masonry'});});$(window).resize(function(){setTimeout(function(){$portfolio.isotope('layout');$blog.isotope('layout');$masonry_block.isotope('layout');},500);});SetParallax();$("#owl-demo").owlCarousel({navigation:true,slideSpeed:300,paginationSpeed:400,singleItem:true,navigationText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"]});$("#owl-demo-small").owlCarousel({navigation:true,slideSpeed:300,paginationSpeed:400,singleItem:true,navigationText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"]});$(".owl-pagination > .owl-page").click(function(e){if($(e.target).is('.mfp-close'))
return;return false;});$(".owl-buttons > .owl-prev").click(function(e){if($(e.target).is('.mfp-close'))
return;return false;});$(".owl-buttons > .owl-next").click(function(e){if($(e.target).is('.mfp-close'))
return;return false;});var sync1=$(".hcode-single-big-product-thumbnail-carousel");var sync2=$(".hcode-single-product-thumbnail-carousel");sync1.owlCarousel({singleItem:true,slideSpeed:1000,navigation:true,pagination:false,navigationText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],afterAction:syncPosition,responsiveRefreshRate:200,});sync2.owlCarousel({items:3,itemsDesktop:[1199,3],itemsDesktopSmall:[979,3],itemsTablet:[768,3],itemsMobile:[479,2],pagination:false,navigation:true,navigationText:["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],responsiveRefreshRate:100,afterInit:function(el){el.find(".owl-item").eq(0).addClass("active");}});function syncPosition(el){var current=this.currentItem;$(".hcode-single-product-thumbnail-carousel").find(".owl-item").removeClass("active").eq(current).addClass("active");if($(".hcode-single-product-thumbnail-carousel").data("owlCarousel")!==undefined){center(current)}}
$(".hcode-single-product-thumbnail-carousel").on("click",".owl-item",function(e){e.preventDefault();var number=$(this).data("owlItem");sync1.trigger("owl.goTo",number);});function center(number){var sync2visible=sync2.data("owlCarousel").owl.visibleItems;var num=number;var found=false;for(var i in sync2visible){if(num===sync2visible[i]){var found=true;}}
if(found===false){if(num>sync2visible[sync2visible.length-1]){sync2.trigger("owl.goTo",num-sync2visible.length+2)}else{if(num-1===-1){num=0;}
sync2.trigger("owl.goTo",num);}}else if(num===sync2visible[sync2visible.length-1]){sync2.trigger("owl.goTo",sync2visible[1])}else if(num===sync2visible[0]){sync2.trigger("owl.goTo",num-1)}}
if(jQuery('section').hasClass('intro-page')){$('section').removeClass('intro-page');$('body').addClass('intro-page');}
var wow=new WOW({boxClass:'wow',animateClass:'animated',offset:90,mobile:false,live:true});wow.init();$('.collapse').on('show.bs.collapse',function(){var id=$(this).attr('id');$('a[href="#'+id+'"]').closest('.panel-heading').addClass('active-accordion');$('a[href="#'+id+'"] .panel-title span').html('<i class="fa fa-minus"></i>');});$('.collapse').on('hide.bs.collapse',function(){var id=$(this).attr('id');$('a[href="#'+id+'"]').closest('.panel-heading').removeClass('active-accordion');$('a[href="#'+id+'"] .panel-title span').html('<i class="fa fa-plus"></i>');});$('.nav.navbar-nav a.inner-link').click(function(){$(this).parents('ul.navbar-nav').find('a.inner-link').removeClass('active');$(this).addClass('active');if($('.navbar-header .navbar-toggle').is(':visible'))
$(this).parents('.navbar-collapse').collapse('hide');});$('.accordion-style2 .collapse').on('show.bs.collapse',function(){var id=$(this).attr('id');$('a[href="#'+id+'"]').closest('.panel-heading').addClass('active-accordion');$('a[href="#'+id+'"] .panel-title span').html('<i class="fa fa-angle-up"></i>');});$('.accordion-style2 .collapse').on('hide.bs.collapse',function(){var id=$(this).attr('id');$('a[href="#'+id+'"]').closest('.panel-heading').removeClass('active-accordion');$('a[href="#'+id+'"] .panel-title span').html('<i class="fa fa-angle-down"></i>');});$('.accordion-style3 .collapse').on('show.bs.collapse',function(){var id=$(this).attr('id');$('a[href="#'+id+'"]').closest('.panel-heading').addClass('active-accordion');$('a[href="#'+id+'"] .panel-title span').html('<i class="fa fa-angle-up"></i>');});$('.accordion-style3 .collapse').on('hide.bs.collapse',function(){var id=$(this).attr('id');$('a[href="#'+id+'"]').closest('.panel-heading').removeClass('active-accordion');$('a[href="#'+id+'"] .panel-title span').html('<i class="fa fa-angle-down"></i>');});$('toggles .collapse').on('show.bs.collapse',function(){var id=$(this).attr('id');$('a[href="#'+id+'"]').closest('.panel-heading').addClass('active-accordion');$('a[href="#'+id+'"] .panel-title span').html('<i class="fa fa-minus"></i>');});$('toggles .collapse').on('hide.bs.collapse',function(){var id=$(this).attr('id');$('a[href="#'+id+'"]').closest('.panel-heading').removeClass('active-accordion');$('a[href="#'+id+'"] .panel-title span').html('<i class="fa fa-plus"></i>');});$('.toggles-style2 .collapse').on('show.bs.collapse',function(){var id=$(this).attr('id');$('a[href="#'+id+'"]').closest('.panel-heading').addClass('active-accordion');$('a[href="#'+id+'"] .panel-title span').html('<i class="fa fa-angle-up"></i>');});$('.toggles-style2 .collapse').on('hide.bs.collapse',function(){var id=$(this).attr('id');$('a[href="#'+id+'"]').closest('.panel-heading').removeClass('active-accordion');$('a[href="#'+id+'"] .panel-title span').html('<i class="fa fa-angle-down"></i>');});try{$(".fit-videos").fitVids();}
catch(err){}
$('#map_canvas1').addClass('scrolloff');$('#canvas1').on('click',function(){$('#map_canvas1').removeClass('scrolloff');});$("#map_canvas1").mouseleave(function(){$('#map_canvas1').addClass('scrolloff');});$("input.search-input").bind("keypress",function(event){if(event.which==13&&!isMobile){$("button.search-button").click();event.preventDefault();}});$("input.search-input").bind("keyup",function(event){if($(this).val()==null||$(this).val()==""){$(this).css({"border":"none","border-bottom":"2px solid red"});}
else{$(this).css({"border":"none","border-bottom":"2px solid #000"});}});function validationSearchForm(){var error=true;$('#search-header input[type=text]').each(function(index){if(index==0){if($(this).val()==null||$(this).val()==""){$("#search-header").find("input:eq("+index+")").css({"border":"none","border-bottom":"2px solid red"});error=false;}
else{$("#search-header").find("input:eq("+index+")").css({"border":"none","border-bottom":"2px solid #000"});}}});return error;}
$("form.search-form, form.search-form-result").submit(function(event){var error=validationSearchForm();if(error){var action=$(this).attr('action');action=action+'?'+$(this).serialize();window.location=action;}
event.preventDefault();});$('.navbar .navbar-collapse a.dropdown-toggle, .accordion-style1 .panel-heading a, .accordion-style2 .panel-heading a, .accordion-style3 .panel-heading a, .toggles .panel-heading a, .toggles-style2 .panel-heading a, .toggles-style3 .panel-heading a, a.carousel-control, .nav-tabs a[data-toggle="tab"], a.shopping-cart').click(function(e){e.preventDefault();});$('body').on('touchstart click',function(e){if($(window).width()<992){if(!$('.navbar-collapse').has(e.target).is('.navbar-collapse')&&$('.navbar-collapse').hasClass('in')&&!$(e.target).hasClass('navbar-toggle')){$('.navbar-collapse').collapse('hide');}}
else{if(!$('.navbar-collapse').has(e.target).is('.navbar-collapse')&&$('.navbar-collapse ul').hasClass('in')){console.log(this);$('.navbar-collapse').find('a.dropdown-toggle').addClass('collapsed');$('.navbar-collapse').find('ul.dropdown-menu').removeClass('in');$('.navbar-collapse a.dropdown-toggle').removeClass('active');}}});$('.navbar-collapse a.dropdown-toggle').on('touchstart',function(e){$('.navbar-collapse a.dropdown-toggle').not(this).removeClass('active');if($(this).hasClass('active'))
$(this).removeClass('active');else
$(this).addClass('active');});$("button.navbar-toggle").click(function(){if(isMobile){jQuery(".cart-content").css('opacity','0');jQuery(".cart-content").css('visibility','hidden');}});$("a.dropdown-toggle").click(function(){if(isMobile){jQuery(".cart-content").css('opacity','0');jQuery(".cart-content").css('visibility','hidden');}});var $elem=$('#content');$('#scroll_to_top').fadeIn('slow');$('#nav_down').fadeIn('slow');$(window).bind('scrollstart',function(){$('#scroll_to_top,#nav_down').stop().animate({'opacity':'0.2'});});$(window).bind('scrollstop',function(){$('#scroll_to_top,#nav_down').stop().animate({'opacity':'1'});});$('#nav_down').click(function(e){$('html, body').animate({scrollTop:$elem.height()},800);});$('#scroll_to_top').click(function(e){$('html, body').animate({scrollTop:'0px'},800);});});$(document).ready(function(){$('.counter-number').appear();$(document.body).on('appear','.counter-number',function(e){var element=$(this);if(!$(this).hasClass('appear')){animatecounters(element);$(this).addClass('appear');}});$('.chart').appear();$(document.body).on('appear','.chart',function(e){var element=$(this);if(!$(this).hasClass('appear')){animatecharts(element);$(this).addClass('appear');}});});function animatecounters(element){var getCounterNumber=jQuery(element).attr('data-to');jQuery({ValuerHbcO:0}).delay(0).animate({ValuerHbcO:getCounterNumber},{duration:2000,easing:"swing",step:function(){$(element).text(Math.ceil(this.ValuerHbcO));}});}
function animatecharts(element){element.data('easyPieChart').update(0);element.data('easyPieChart').update(element.attr("data-percent"));}
$(window).scroll(function(){if($(window).scrollTop()>10){$('nav').addClass('shrink-nav');}else{$('nav').removeClass('shrink-nav');}});function SetResizeHeaderMenu(){var width=jQuery('nav.navbar').children('div.container').width();$("ul.mega-menu-full").each(function(){jQuery(this).css('width',width+'px');});}
$('.parallax-fix').each(function(){if($(this).children('.parallax-background-img').length){var imgSrc=jQuery(this).children('.parallax-background-img').attr('src');jQuery(this).css('background','url("'+imgSrc+'")');jQuery(this).children('.parallax-background-img').remove();$(this).css('background-position','50% 0%');}});var IsParallaxGenerated=false;function SetParallax(){if($(window).width()>1030&&!IsParallaxGenerated){$('.parallax1').parallax("50%",0.1);$('.parallax2').parallax("50%",0.2);$('.parallax3').parallax("50%",0.3);$('.parallax4').parallax("50%",0.4);$('.parallax5').parallax("50%",0.5);$('.parallax6').parallax("50%",0.6);$('.parallax7').parallax("50%",0.7);$('.parallax8').parallax("50%",0.8);$('.parallax9').parallax("50%",0.05);$('.parallax10').parallax("50%",0.02);$('.parallax11').parallax("50%",0.01);$('.parallax12').parallax("50%",0.099);IsParallaxGenerated=true;}}
$('.mobile-toggle').click(function(){$('nav').toggleClass('open-nav');});$('.dropdown-arrow').click(function(){if($('.mobile-toggle').is(":visible")){if($(this).children('.dropdown').hasClass('open-nav')){$(this).children('.dropdown').removeClass('open-nav');}else{$('.dropdown').removeClass('open-nav');$(this).children('.dropdown').addClass('open-nav');}}});$("form.wpcf7-form input").focus(function(){if($(this).hasClass("wpcf7-not-valid")){$(this).removeClass("wpcf7-not-valid");$(this).parent().find(".wpcf7-not-valid-tip").remove();$(this).parents().find(".wpcf7-validation-errors").css("display","none");}});$('.dropdown-fullwidth').each(function(){$(this).css('width',$('.row').width());var subNavOffset=-($('nav .row').innerWidth()-$('.menu').innerWidth()-15);$(this).css('left',subNavOffset);});var scrollAnimationTime=1200,scrollAnimation='easeInOutExpo';$('a.scrollto').bind('click.smoothscroll',function(event){event.preventDefault();var target=this.hash;$('html, body').stop().animate({'scrollTop':$(target).offset().top},scrollAnimationTime,scrollAnimation,function(){window.location.hash=target;});});$('.inner-link').smoothScroll({speed:900,offset:-0});$('section.scrollToDownSection').click(function(){var section_id=$($(this).attr('data-section-id'));$('html, body').animate({scrollTop:section_id.offset().top},800);});function SetResizeContent(){var minheight=$(window).height();$(".full-screen").css('min-height',minheight);var minwidth=$(window).width();$(".full-screen-width").css('min-width',minwidth);}
SetResizeContent();$(window).resize(function(){$('.dropdown-fullwidth').each(function(){$(this).css('width',$('.row').width());var subNavOffset=-($('nav .row').innerWidth()-$('.menu').innerWidth()-15);$(this).css('left',subNavOffset);});SetResizeContent();setTimeout(function(){SetResizeHeaderMenu();},200);if($(window).width()>=992&&$('.navbar-collapse').hasClass('in')){$('.navbar-collapse').removeClass('in');$('.navbar-collapse ul.dropdown-menu').each(function(){if($(this).hasClass('in')){$(this).removeClass('in');}});$('ul.navbar-nav > li.dropdown > a.dropdown-toggle').addClass('collapsed');$('.logo').focus();$('.navbar-collapse a.dropdown-toggle').removeClass('active');}
setTimeout(function(){SetParallax();},1000);});if($('.counter-hidden').hasClass('counter-underconstruction-date')){var $counter_date=$('.counter-underconstruction-date').html();$('#counter-underconstruction').countdown($counter_date+' 12:00:00').on('update.countdown',function(event){var $this=$(this).html(event.strftime(''+'<div class="counter-container"><div class="counter-box first"><div class="number">%-D</div><span>Day%!d</span></div>'+'<div class="counter-box"><div class="number">%H</div><span>Hours</span></div>'+'<div class="counter-box"><div class="number">%M</div><span>Minutes</span></div>'+'<div class="counter-box last"><div class="number">%S</div><span>Seconds</span></div></div>'))});}
if($('.counter-hidden').hasClass('hcode-time-counter-date')){var $counter_date=$('.hcode-time-counter-date').html();$('#hcode-time-counter').countdown($counter_date+' 12:00:00').on('update.countdown',function(event){var $this=$(this).html(event.strftime(''+'<div class="counter-container"><div class="counter-box first"><div class="number">%-D</div><span>Day%!d</span></div>'+'<div class="counter-box"><div class="number">%H</div><span>Hours</span></div>'+'<div class="counter-box"><div class="number">%M</div><span>Minutes</span></div>'+'<div class="counter-box last"><div class="number">%S</div><span>Seconds</span></div></div>'))});}
$(window).scroll(function(){if($(this).scrollTop()>100){$('.scrollToTop').fadeIn();}else{$('.scrollToTop').fadeOut();}});$('.scrollToTop').click(function(){$('html, body').animate({scrollTop:0},1000);return false;});$(".carousel .carousel-indicators > li:first-child").addClass("active");$(".carousel .carousel-inner > div:first-child").addClass("active");$('span.optionsradios input[value=Disabled]').attr('disabled','disabled');$('span.optionscheckbox input[value=Disabled]').attr('disabled','disabled');$('.submit_newsletter').click(function(){var reg=/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;var current=$(this);var address=$(this).closest('form').find('.xyz_em_email').val();if(reg.test(address)==false){current.closest('form').find('.xyz_em_email').addClass('newsletter-error');return false;}else{return true;}});$('.xyz_em_email').on('focus',function(){$(this).removeClass('newsletter-error');});if($('div').hasClass('feature_nav')){$(".feature_nav .next").click(function(){$(this).parent().parent().find('.owl-carousel').trigger('owl.next');});$(".feature_nav .prev").click(function(){$(this).parent().parent().find('.owl-carousel').trigger('owl.prev');});}
$('.hcode-product-grid-list-wrapper > a').click(function(){var set_product_view=$(this);var product_type=set_product_view.parents().find('.product-main-wrapper > .products');if(set_product_view.hasClass('hcode-list-view')){product_type.addClass('product-list-view');product_type.removeClass('product-grid-view');}
if(set_product_view.hasClass('hcode-grid-view')){product_type.addClass('product-grid-view');product_type.removeClass('product-list-view');}
set_product_view.parent().find('.active').removeClass('active');set_product_view.addClass('active');});$(document).ready(function(){$('div.quantity:not(.buttons_added), wc-new td.quantity:not(.buttons_added)').addClass('buttons_added').append('<input type="button" value="+" class="plus" />').prepend('<input type="button" value="-" class="minus" />');$('input.qty:not(.product-quantity input.qty)').each(function(){var min=parseFloat($(this).attr('min'));if(min&&min>0&&parseFloat($(this).val())<min){$(this).val(min);}});$(document).on('click','.plus, .minus',function(){var $qty=$(this).closest('.quantity').find('.qty'),currentVal=parseFloat($qty.val()),max=parseFloat($qty.attr('max')),min=parseFloat($qty.attr('min')),step=$qty.attr('step');if(!currentVal||currentVal===''||currentVal==='NaN')currentVal=0;if(max===''||max==='NaN')max='';if(min===''||min==='NaN')min=0;if(step==='any'||step===''||step===undefined||parseFloat(step)==='NaN')step=1;if($(this).is('.plus')){if(max&&(max==currentVal||currentVal>max)){$qty.val(max);}else{$qty.val(currentVal+parseFloat(step));}}else{if(min&&(min==currentVal||currentVal<min)){$qty.val(min);}else if(currentVal>0){$qty.val(currentVal-parseFloat(step));}}
$qty.trigger('change');});});$(document).ready(function(){$(document).on('click','.checkout-alert-remove',function(){var remove_parent=$(this).parent().parent();if(remove_parent.hasClass('alert-remove')){remove_parent.remove();}});});$(document).ready(function(){$(document).on('click','.sl-button',function(){var button=$(this);var post_id=button.attr('data-post-id');var security=button.attr('data-nonce');var iscomment=button.attr('data-iscomment');var allbuttons;if(iscomment==='1'){allbuttons=$('.sl-comment-button-'+post_id);}else{allbuttons=$('.sl-button-'+post_id);}
var loader=allbuttons.next('#sl-loader');if(post_id!==''){$.ajax({type:'POST',url:simpleLikes.ajaxurl,data:{action:'process_simple_like',post_id:post_id,nonce:security,is_comment:iscomment},beforeSend:function(){},success:function(response){var icon=response.icon;var count=response.count;allbuttons.html(icon+count);if(response.status==='unliked'){var like_text=simpleLikes.like;allbuttons.prop('title',like_text);allbuttons.removeClass('liked');}else{var unlike_text=simpleLikes.unlike;allbuttons.prop('title',unlike_text);allbuttons.addClass('liked');}
loader.empty();}});}
return false;});});$(document).ready(function(){$(document).on('click','.menu-first-level > a:first-child',function(){var geturl=$(this).attr('data-redirect-url');if(geturl!='#'&&geturl!=''){if($(this).attr('target')=='_blank'){window.open(geturl,'_blank');}else{window.location=geturl;}}});});$(document).ready(function(){$(".comment-button").on("click",function(){var fields;fields="";if($(this).parent().parent().find('#author').length==1){if($("#author").val().length==0||$("#author").val().value=='')
{fields='1';$("#author").addClass("inputerror");}}
if($(this).parent().parent().find('#comment').length==1){if($("#comment").val().length==0||$("#comment").val().value=='')
{fields='1';$("#comment").addClass("inputerror");}}
if($(this).parent().parent().find('#email').length==1){if($("#email").val().length==0||$("#email").val().length=='')
{fields='1';$("#email").addClass("inputerror");}
else
{var re=new RegExp();re=/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;var sinput;sinput="";sinput=$("#email").val();if(!re.test(sinput))
{fields='1';$("#email").addClass("inputerror");}}}
if(fields!="")
{return false;}
else
{return true;}});});function inputfocus(id){$('#'+id).removeClass('inputerror');}
var IpadMobileHover=function(){if((navigator.userAgent.match(/iPhone/i))||(navigator.userAgent.match(/iPod/i))||(navigator.userAgent.match(/iPad/i))){$('.icon-box > i').on('touchstart',function(){$(this).trigger('hover');}).on('touchend',function(){$(this).trigger('hover');});}};;var addComment={moveForm:function(a,b,c,d){var e,f,g,h,i=this,j=i.I(a),k=i.I(c),l=i.I("cancel-comment-reply-link"),m=i.I("comment_parent"),n=i.I("comment_post_ID"),o=k.getElementsByTagName("form")[0];if(j&&k&&l&&m&&o){i.respondId=c,d=d||!1,i.I("wp-temp-form-div")||(e=document.createElement("div"),e.id="wp-temp-form-div",e.style.display="none",k.parentNode.insertBefore(e,k)),j.parentNode.insertBefore(k,j.nextSibling),n&&d&&(n.value=d),m.value=b,l.style.display="",l.onclick=function(){var a=addComment,b=a.I("wp-temp-form-div"),c=a.I(a.respondId);if(b&&c)return a.I("comment_parent").value="0",b.parentNode.insertBefore(c,b),b.parentNode.removeChild(b),this.style.display="none",this.onclick=null,!1};try{for(var p=0;p<o.elements.length;p++)if(f=o.elements[p],h=!1,"getComputedStyle"in window?g=window.getComputedStyle(f):document.documentElement.currentStyle&&(g=f.currentStyle),(f.offsetWidth<=0&&f.offsetHeight<=0||"hidden"===g.visibility)&&(h=!0),"hidden"!==f.type&&!f.disabled&&!h){f.focus();break}}catch(q){}return!1}},I:function(a){return document.getElementById(a)}};;!function(a,b){"use strict";function c(){if(!e){e=!0;var a,c,d,f,g=-1!==navigator.appVersion.indexOf("MSIE 10"),h=!!navigator.userAgent.match(/Trident.*rv:11\./),i=b.querySelectorAll("iframe.wp-embedded-content"),j=b.querySelectorAll("blockquote.wp-embedded-content");for(c=0;c<j.length;c++)j[c].style.display="none";for(c=0;c<i.length;c++)if(d=i[c],d.style.display="",!d.getAttribute("data-secret")){if(f=Math.random().toString(36).substr(2,10),d.src+="#?secret="+f,d.setAttribute("data-secret",f),g||h)a=d.cloneNode(!0),a.removeAttribute("security"),d.parentNode.replaceChild(a,d)}else;}}var d=!1,e=!1;if(b.querySelector)if(a.addEventListener)d=!0;if(a.wp=a.wp||{},!a.wp.receiveEmbedMessage)if(a.wp.receiveEmbedMessage=function(c){var d=c.data;if(d.secret||d.message||d.value)if(!/[^a-zA-Z0-9]/.test(d.secret)){var e,f,g,h,i,j=b.querySelectorAll('iframe[data-secret="'+d.secret+'"]'),k=b.querySelectorAll('blockquote[data-secret="'+d.secret+'"]');for(e=0;e<k.length;e++)k[e].style.display="none";for(e=0;e<j.length;e++)if(f=j[e],c.source===f.contentWindow){if(f.style.display="","height"===d.message){if(g=parseInt(d.value,10),g>1e3)g=1e3;else if(200>~~g)g=200;f.height=g}if("link"===d.message)if(h=b.createElement("a"),i=b.createElement("a"),h.href=f.getAttribute("src"),i.href=d.value,i.host===h.host)if(b.activeElement===f)a.top.location.href=d.value}else;}},d)a.addEventListener("message",a.wp.receiveEmbedMessage,!1),b.addEventListener("DOMContentLoaded",c,!1),a.addEventListener("load",c,!1)}(window,document);